# Generated by Django 3.2.9 on 2021-11-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='room',
            field=models.UUIDField(),
        ),
    ]
